name: test-geospatial-images-plugin

on:
    workflow_dispatch:
    pull_request:
      branches:
        - main
        - '[0-9]*.[0-9]*.[0-9]*-nightly'
      paths:
        - 'datagenerators/geospatial-images/plugin/**'
        - '.github/workflows/geospatial-images-plugin-test.yaml'


jobs:
  test-geospatial-images-plugin-amd64:
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write

    uses: microsoft/azure-orbital-space-sdk-github-actions/.github/workflows/test-plugin.yaml@0.11.0-nightly
    with:
      APP_NAME: vth
      PLUGIN_NAME: geospatial-images-vth-plugin
      WORKFLOW_AGENT: ubuntu-latest
      DEVCONTAINER_JSON: ./.devcontainer/geospatial-images-vth-plugin/devcontainer.json
      REPO_DIR: ./datagenerators/geospatial-images/plugin
    secrets:
      GIT_HUB_USER_NAME: ${{ secrets.GIT_HUB_USER_NAME }}
      GIT_HUB_USER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SETUP_REPO_URL: ${{ secrets.SETUP_REPO_URL }}
      

  test-geospatial-images-plugin-arm64:
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write

    uses: microsoft/azure-orbital-space-sdk-github-actions/.github/workflows/test-plugin.yaml@0.11.0-nightly
    with:
      APP_NAME: vth
      PLUGIN_NAME: geospatial-images-vth-plugin
      WORKFLOW_AGENT: spacesdk-ubuntu-2204LTS-arm64
      DEVCONTAINER_JSON: ./.devcontainer/geospatial-images-vth-plugin/devcontainer.json
      REPO_DIR: ./datagenerators/geospatial-images/plugin
    secrets:
      GIT_HUB_USER_NAME: ${{ secrets.GIT_HUB_USER_NAME }}
      GIT_HUB_USER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SETUP_REPO_URL: ${{ secrets.SETUP_REPO_URL }}