name: planetary-computer-dg-build

on: 
    workflow_dispatch:
    push:
        branches:
         - main
         - '[0-9]*.[0-9]*.[0-9]*-nightly'
        paths:
        - 'datagenerators/planetary-computer/datagenerator/**'
        - '.github/workflows/planetary-computer-generator-build.yaml'

jobs:
  build-datagenerator-planetary-computer-amd64:
    permissions:
      contents: read
      packages: write

    uses: microsoft/azure-orbital-space-sdk-github-actions/.github/workflows/data-generator-build.yaml@0.11.0-nightly
    with:
      REGISTRY: ghcr.io
      APP_NAME: datagenerator-planetary-computer
      ANNOTATION: azure-orbital-space-sdk-data-generators.yaml
      WORKFLOW_AGENT: ubuntu-latest
      ARCHITECTURE: amd64
      DOCKER_FILE: ./datagenerators/planetary-computer/datagenerator/Dockerfiles/Dockerfile
      REPO_DIR: ./datagenerators/planetary-computer/datagenerator
      YAML_STAGING_DIRECTORY: /var/spacedev/yamls
      YAML_FOLDER_PATH: ./datagenerators/planetary-computer/datagenerator/k3s
      YAML_FILE_NAME: datagenerator-planetary-computer.yaml
    secrets:
      GIT_HUB_USER_NAME: ${{ secrets.GIT_HUB_USER_NAME }}
      GIT_HUB_USER_TOKEN: ${{ secrets.GIT_HUB_USER_TOKEN }}
      SETUP_REPO_URL: ${{ secrets.SETUP_REPO_URL }}

  build-datagenerator-planetary-computer-arm64:
    permissions:
      contents: read
      packages: write

    uses: microsoft/azure-orbital-space-sdk-github-actions/.github/workflows/data-generator-build.yaml@0.11.0-nightly
    with:
      REGISTRY: ghcr.io
      APP_NAME: datagenerator-planetary-computer
      ANNOTATION: azure-orbital-space-sdk-data-generators.yaml
      WORKFLOW_AGENT: spacesdk-ubuntu-2204LTS-arm64
      ARCHITECTURE: arm64
      DOCKER_FILE: ./datagenerators/planetary-computer/datagenerator/Dockerfiles/Dockerfile
      REPO_DIR: ./datagenerators/planetary-computer/datagenerator
      YAML_STAGING_DIRECTORY: /var/spacedev/yamls
      YAML_FOLDER_PATH: ./datagenerators/planetary-computer/datagenerator/k3s
      YAML_FILE_NAME: datagenerator-planetary-computer.yaml
    secrets:
      GIT_HUB_USER_NAME: ${{ secrets.GIT_HUB_USER_NAME }}
      GIT_HUB_USER_TOKEN: ${{ secrets.GIT_HUB_USER_TOKEN }}
      SETUP_REPO_URL: ${{ secrets.SETUP_REPO_URL }}